// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using gip.core.datamodel;

#pragma warning disable 219, 612, 618
#nullable disable

namespace iPlusV5CompiledModels
{
    [DbContext(typeof(iPlusV4Context))]
    public partial class iPlusV4ContextModel : RuntimeModel
    {
        static iPlusV4ContextModel()
        {
            var model = new iPlusV4ContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static iPlusV4ContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
