// Copyright (c) 2024, gipSoft d.o.o.
// Licensed under the GNU GPLv3 License. See LICENSE file in the project root for full license information.
﻿using gip.core.datamodel;

namespace gip.core.reporthandlerwpf
{
    /// <summary>
    /// Return value for actual command status
    /// </summary>
    [ACSerializeableInfo]
    [ACClassInfo("gip.VarioSystem", "en{'LinxCommandStatusCodeEnum'}de{'LinxCommandStatusCodeEnum'}", Global.ACKinds.TACEnum, Global.ACStorableTypes.NotStorable, false, false, "", "", 9999)]
    public enum LinxCommandStatusCodeEnum : byte
    {
        None = 0,
        Parity_error = 0x01,
        Framing_error = 0x02,
        Data_overrun = 0x03,
        Serial_break = 0x04,
        Receive_buffer_Overflow = 0x05,
        Command_start = 0x06,
        Command_end = 0x07,
        Invalid_checksum = 0x08,
        Reserved = 0x09,
        Reserved1 = 0x0A,
        Reserved2 = 0x0B,
        Reserved3 = 0x0C,
        Reserved4 = 0x0D,
        Reserved5 = 0x0E,
        Reserved6 = 0x0F,
        Reserved7 = 0x10,
        Invalid_command = 0x11,
        Jet_not_running = 0x12,
        Jet_not_idle = 0x13,
        Print_not_idle = 0x14,

        Message_edit_in_progress = 0x15,
        Number_of_bytes_in_command = 0x16,
        Parameter_rejected = 0x17,
        Minimum_string_length = 0x18,
        Maximum_string_length = 0x19,
        Minimum_value = 0x1A,
        Maximum_value = 0x1B,
        Memory_full = 0x1C,

        No_character_sets = 0x1D,
        No_bar_codes = 0x1E,
        No_logos = 0x1F,
        No_date_formats = 0x20,
        PROM_based_data_set_specified = 0x21,
        Unknown_data_set = 0x22,
        No_messages = 0x23,
        Unknown_message = 0x24,
        Field_too_large = 0x25,
        Additional_message_overwrite = 0x26,
        Non_alphanumeric_character = 0x27,
        Positive_value = 0x28,
        Trigger_print_Photocell_mode = 0x29,
        Trigger_print_Print_idle = 0x2A,
        Trigger_print_Already_printing = 0x2B,
        Trigger_print_Cover_off = 0x2C,
        Print_command_Jet_not_running = 0x2D,
        Print_command_No_message = 0x2E,
        Jet_command_Ink_low = 0x2F,
        Jet_command_Solvent_low = 0x30,
        Jet_command_Print_fail = 0x31,
        Jet_command_Print_in_progress = 0x32,
        Jet_command_Phase = 0x33,
        Jet_command_Time_of_flight = 0x34,
        Cal_printhead_Try_later = 0x35,
        Cal_printhead_Failed = 0x36,
        Message_too_large = 0x37,
        Pixel_RAM_overflow = 0x38,
        Invalid_message_format = 0x39,
        Invalid_field_type = 0x3A,
        No_print_message_loaded = 0x3B,

        Invalid_print_mode = 0x3C,
        Invalid_failure_condition = 0x3D,
        Invalid_buffer_divisor = 0x3E,
        No_remote_fields_in_message = 0x3F,
        Number_of_remote_characters = 0x40,
        Remote_data_too_large = 0x41,
        Remote_buffer_now_full = 0x42,
        Remote_buffer_still_full = 0x43,
        Field_data_exceeds_message_end = 0x44,
        Invalid_remote_field_type = 0x45,
        Invalid_while_display_enabled = 0x46,
        Reserved8 = 0x47,
        Reserved9 = 0x48,
        Reserved10 = 0x49,
        Reserved11 = 0x4A,
        Reserved12 = 0x4B,
        Reserved13 = 0x4C,
        Reserved14 = 0x4D,
        Reserved15 = 0x4E,
        Too_many_messages_specified = 0x4F,
        Reserved16 = 0x50,
        Printer_busy = 0x51,
        Unknown_raster = 0x52,
        Invalid_field_length = 0x53,
        Duplicate_name = 0x54,
        Invalid_bar_code_linkage = 0x55,
        Data_set_in_ROM = 0x56,
        Data_set_in_use = 0x57,
        Invalid_field_height = 0x58,
        Production_Schedule_No_message_schedules = 0x59,
        Production_Schedule_Too_many_message_schedules = 0x5A,
        Production_Schedule_Unknown_message_schedule = 0x5B,
        Production_Schedule_Duplicate_message_schedule = 0x5C,
        Overlapping_fields = 0x5D,
        Not_Calibrated = 0x5E,
        Production_Schedule_Incorrect_Trigger_Mapping = 0x5F
    }
}
