// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace gip.core.datamodel
{
    public partial class iPlusV5ContextModel
    {
        private iPlusV5ContextModel()
            : base(skipDetectChanges: true, modelId: new Guid("d6cfc3d8-9f2b-4baa-95a8-767ca4d5337e"), entityTypeCount: 47)
        {
        }

        partial void Initialize()
        {
            var aCAssembly = ACAssemblyEntityType.Create(this);
            var aCChangeLog = ACChangeLogEntityType.Create(this);
            var aCClass = ACClassEntityType.Create(this);
            var aCClassConfig = ACClassConfigEntityType.Create(this);
            var aCClassDesign = ACClassDesignEntityType.Create(this);
            var aCClassMessage = ACClassMessageEntityType.Create(this);
            var aCClassMethod = ACClassMethodEntityType.Create(this);
            var aCClassMethodConfig = ACClassMethodConfigEntityType.Create(this);
            var aCClassProperty = ACClassPropertyEntityType.Create(this);
            var aCClassPropertyRelation = ACClassPropertyRelationEntityType.Create(this);
            var aCClassRouteUsage = ACClassRouteUsageEntityType.Create(this);
            var aCClassRouteUsageGroup = ACClassRouteUsageGroupEntityType.Create(this);
            var aCClassRouteUsagePos = ACClassRouteUsagePosEntityType.Create(this);
            var aCClassTask = ACClassTaskEntityType.Create(this);
            var aCClassTaskValue = ACClassTaskValueEntityType.Create(this);
            var aCClassTaskValuePos = ACClassTaskValuePosEntityType.Create(this);
            var aCClassText = ACClassTextEntityType.Create(this);
            var aCClassWF = ACClassWFEntityType.Create(this);
            var aCClassWFEdge = ACClassWFEdgeEntityType.Create(this);
            var aCPackage = ACPackageEntityType.Create(this);
            var aCProgram = ACProgramEntityType.Create(this);
            var aCProgramConfig = ACProgramConfigEntityType.Create(this);
            var aCProgramLog = ACProgramLogEntityType.Create(this);
            var aCProgramLogPropertyLog = ACProgramLogPropertyLogEntityType.Create(this);
            var aCProgramLogTask = ACProgramLogTaskEntityType.Create(this);
            var aCProject = ACProjectEntityType.Create(this);
            var aCPropertyLog = ACPropertyLogEntityType.Create(this);
            var aCPropertyLogRule = ACPropertyLogRuleEntityType.Create(this);
            var controlScriptSyncInfo = ControlScriptSyncInfoEntityType.Create(this);
            var dBSyncerVersion = DBSyncerVersionEntityType.Create(this);
            var dbSyncerInfo = DbSyncerInfoEntityType.Create(this);
            var dbSyncerInfoContext = DbSyncerInfoContextEntityType.Create(this);
            var msgAlarmLog = MsgAlarmLogEntityType.Create(this);
            var vBConfig = VBConfigEntityType.Create(this);
            var vBGroup = VBGroupEntityType.Create(this);
            var vBGroupRight = VBGroupRightEntityType.Create(this);
            var vBLanguage = VBLanguageEntityType.Create(this);
            var vBLicense = VBLicenseEntityType.Create(this);
            var vBNoConfiguration = VBNoConfigurationEntityType.Create(this);
            var vBSystem = VBSystemEntityType.Create(this);
            var vBSystemColumns = VBSystemColumnsEntityType.Create(this);
            var vBTranslationView = VBTranslationViewEntityType.Create(this);
            var vBUser = VBUserEntityType.Create(this);
            var vBUserACClassDesign = VBUserACClassDesignEntityType.Create(this);
            var vBUserACProject = VBUserACProjectEntityType.Create(this);
            var vBUserGroup = VBUserGroupEntityType.Create(this);
            var vBUserInstance = VBUserInstanceEntityType.Create(this);

            ACChangeLogEntityType.CreateForeignKey1(aCChangeLog, aCClass);
            ACChangeLogEntityType.CreateForeignKey2(aCChangeLog, aCClassProperty);
            ACChangeLogEntityType.CreateForeignKey3(aCChangeLog, vBUser);
            ACClassEntityType.CreateForeignKey1(aCClass, aCPackage);
            ACClassEntityType.CreateForeignKey2(aCClass, aCProject);
            ACClassEntityType.CreateForeignKey3(aCClass, aCClass);
            ACClassEntityType.CreateForeignKey4(aCClass, aCClass);
            ACClassEntityType.CreateForeignKey5(aCClass, aCClass);
            ACClassEntityType.CreateForeignKey6(aCClass, aCClass);
            ACClassConfigEntityType.CreateForeignKey1(aCClassConfig, aCClass);
            ACClassConfigEntityType.CreateForeignKey2(aCClassConfig, aCClassPropertyRelation);
            ACClassConfigEntityType.CreateForeignKey3(aCClassConfig, aCClassConfig);
            ACClassConfigEntityType.CreateForeignKey4(aCClassConfig, aCClass);
            ACClassDesignEntityType.CreateForeignKey1(aCClassDesign, aCClass);
            ACClassDesignEntityType.CreateForeignKey2(aCClassDesign, aCClass);
            ACClassMessageEntityType.CreateForeignKey1(aCClassMessage, aCClass);
            ACClassMethodEntityType.CreateForeignKey1(aCClassMethod, aCClass);
            ACClassMethodEntityType.CreateForeignKey2(aCClassMethod, aCClass);
            ACClassMethodEntityType.CreateForeignKey3(aCClassMethod, aCClass);
            ACClassMethodEntityType.CreateForeignKey4(aCClassMethod, aCClassMethod);
            ACClassMethodEntityType.CreateForeignKey5(aCClassMethod, aCClass);
            ACClassMethodConfigEntityType.CreateForeignKey1(aCClassMethodConfig, aCClassMethod);
            ACClassMethodConfigEntityType.CreateForeignKey2(aCClassMethodConfig, aCClassWF);
            ACClassMethodConfigEntityType.CreateForeignKey3(aCClassMethodConfig, aCClassMethodConfig);
            ACClassMethodConfigEntityType.CreateForeignKey4(aCClassMethodConfig, aCClass);
            ACClassMethodConfigEntityType.CreateForeignKey5(aCClassMethodConfig, aCClassPropertyRelation);
            ACClassMethodConfigEntityType.CreateForeignKey6(aCClassMethodConfig, aCClass);
            ACClassPropertyEntityType.CreateForeignKey1(aCClassProperty, aCClass);
            ACClassPropertyEntityType.CreateForeignKey2(aCClassProperty, aCClassProperty);
            ACClassPropertyEntityType.CreateForeignKey3(aCClassProperty, aCClass);
            ACClassPropertyEntityType.CreateForeignKey4(aCClassProperty, aCClassProperty);
            ACClassPropertyEntityType.CreateForeignKey5(aCClassProperty, aCClass);
            ACClassPropertyRelationEntityType.CreateForeignKey1(aCClassPropertyRelation, aCClass);
            ACClassPropertyRelationEntityType.CreateForeignKey2(aCClassPropertyRelation, aCClassProperty);
            ACClassPropertyRelationEntityType.CreateForeignKey3(aCClassPropertyRelation, aCClass);
            ACClassPropertyRelationEntityType.CreateForeignKey4(aCClassPropertyRelation, aCClassProperty);
            ACClassRouteUsageGroupEntityType.CreateForeignKey1(aCClassRouteUsageGroup, aCClassRouteUsage);
            ACClassRouteUsagePosEntityType.CreateForeignKey1(aCClassRouteUsagePos, aCClassRouteUsage);
            ACClassTaskEntityType.CreateForeignKey1(aCClassTask, aCProgram);
            ACClassTaskEntityType.CreateForeignKey2(aCClassTask, aCClassWF);
            ACClassTaskEntityType.CreateForeignKey3(aCClassTask, aCClassTask);
            ACClassTaskEntityType.CreateForeignKey4(aCClassTask, aCClass);
            ACClassTaskValueEntityType.CreateForeignKey1(aCClassTaskValue, aCClassProperty);
            ACClassTaskValueEntityType.CreateForeignKey2(aCClassTaskValue, aCClassTask);
            ACClassTaskValueEntityType.CreateForeignKey3(aCClassTaskValue, vBUser);
            ACClassTaskValuePosEntityType.CreateForeignKey1(aCClassTaskValuePos, aCClassTaskValue);
            ACClassTextEntityType.CreateForeignKey1(aCClassText, aCClass);
            ACClassWFEntityType.CreateForeignKey1(aCClassWF, aCClassMethod);
            ACClassWFEntityType.CreateForeignKey2(aCClassWF, aCClass);
            ACClassWFEntityType.CreateForeignKey3(aCClassWF, aCClassWF);
            ACClassWFEntityType.CreateForeignKey4(aCClassWF, aCClass);
            ACClassWFEntityType.CreateForeignKey5(aCClassWF, aCClassMethod);
            ACClassWFEdgeEntityType.CreateForeignKey1(aCClassWFEdge, aCClassMethod);
            ACClassWFEdgeEntityType.CreateForeignKey2(aCClassWFEdge, aCClassMethod);
            ACClassWFEdgeEntityType.CreateForeignKey3(aCClassWFEdge, aCClassProperty);
            ACClassWFEdgeEntityType.CreateForeignKey4(aCClassWFEdge, aCClassWF);
            ACClassWFEdgeEntityType.CreateForeignKey5(aCClassWFEdge, aCClassMethod);
            ACClassWFEdgeEntityType.CreateForeignKey6(aCClassWFEdge, aCClassProperty);
            ACClassWFEdgeEntityType.CreateForeignKey7(aCClassWFEdge, aCClassWF);
            ACProgramEntityType.CreateForeignKey1(aCProgram, aCClassMethod);
            ACProgramEntityType.CreateForeignKey2(aCProgram, aCClass);
            ACProgramConfigEntityType.CreateForeignKey1(aCProgramConfig, aCClass);
            ACProgramConfigEntityType.CreateForeignKey2(aCProgramConfig, aCClassPropertyRelation);
            ACProgramConfigEntityType.CreateForeignKey3(aCProgramConfig, aCProgram);
            ACProgramConfigEntityType.CreateForeignKey4(aCProgramConfig, aCProgramConfig);
            ACProgramConfigEntityType.CreateForeignKey5(aCProgramConfig, aCClass);
            ACProgramLogEntityType.CreateForeignKey1(aCProgramLog, aCProgram);
            ACProgramLogEntityType.CreateForeignKey2(aCProgramLog, aCProgramLog);
            ACProgramLogPropertyLogEntityType.CreateForeignKey1(aCProgramLogPropertyLog, aCPropertyLog);
            ACProgramLogTaskEntityType.CreateForeignKey1(aCProgramLogTask, aCProgramLog);
            ACProjectEntityType.CreateForeignKey1(aCProject, aCProject);
            ACProjectEntityType.CreateForeignKey2(aCProject, aCClass);
            ACPropertyLogEntityType.CreateForeignKey1(aCPropertyLog, aCClass);
            ACPropertyLogEntityType.CreateForeignKey2(aCPropertyLog, aCClassProperty);
            ACPropertyLogRuleEntityType.CreateForeignKey1(aCPropertyLogRule, aCClass);
            DbSyncerInfoEntityType.CreateForeignKey1(dbSyncerInfo, dbSyncerInfoContext);
            MsgAlarmLogEntityType.CreateForeignKey1(msgAlarmLog, aCClass);
            MsgAlarmLogEntityType.CreateForeignKey2(msgAlarmLog, aCProgramLog);
            VBConfigEntityType.CreateForeignKey1(vBConfig, aCClass);
            VBConfigEntityType.CreateForeignKey2(vBConfig, aCClassPropertyRelation);
            VBConfigEntityType.CreateForeignKey3(vBConfig, vBConfig);
            VBConfigEntityType.CreateForeignKey4(vBConfig, aCClass);
            VBGroupRightEntityType.CreateForeignKey1(vBGroupRight, aCClassDesign);
            VBGroupRightEntityType.CreateForeignKey2(vBGroupRight, aCClass);
            VBGroupRightEntityType.CreateForeignKey3(vBGroupRight, aCClassMethod);
            VBGroupRightEntityType.CreateForeignKey4(vBGroupRight, aCClassProperty);
            VBGroupRightEntityType.CreateForeignKey5(vBGroupRight, vBGroup);
            VBUserEntityType.CreateForeignKey1(vBUser, aCClassDesign);
            VBUserEntityType.CreateForeignKey2(vBUser, vBLanguage);
            VBUserACClassDesignEntityType.CreateForeignKey1(vBUserACClassDesign, aCClassDesign);
            VBUserACClassDesignEntityType.CreateForeignKey2(vBUserACClassDesign, vBUser);
            VBUserACProjectEntityType.CreateForeignKey1(vBUserACProject, aCProject);
            VBUserACProjectEntityType.CreateForeignKey2(vBUserACProject, vBUser);
            VBUserGroupEntityType.CreateForeignKey1(vBUserGroup, vBGroup);
            VBUserGroupEntityType.CreateForeignKey2(vBUserGroup, vBUser);
            VBUserInstanceEntityType.CreateForeignKey1(vBUserInstance, vBUser);

            ACAssemblyEntityType.CreateAnnotations(aCAssembly);
            ACChangeLogEntityType.CreateAnnotations(aCChangeLog);
            ACClassEntityType.CreateAnnotations(aCClass);
            ACClassConfigEntityType.CreateAnnotations(aCClassConfig);
            ACClassDesignEntityType.CreateAnnotations(aCClassDesign);
            ACClassMessageEntityType.CreateAnnotations(aCClassMessage);
            ACClassMethodEntityType.CreateAnnotations(aCClassMethod);
            ACClassMethodConfigEntityType.CreateAnnotations(aCClassMethodConfig);
            ACClassPropertyEntityType.CreateAnnotations(aCClassProperty);
            ACClassPropertyRelationEntityType.CreateAnnotations(aCClassPropertyRelation);
            ACClassRouteUsageEntityType.CreateAnnotations(aCClassRouteUsage);
            ACClassRouteUsageGroupEntityType.CreateAnnotations(aCClassRouteUsageGroup);
            ACClassRouteUsagePosEntityType.CreateAnnotations(aCClassRouteUsagePos);
            ACClassTaskEntityType.CreateAnnotations(aCClassTask);
            ACClassTaskValueEntityType.CreateAnnotations(aCClassTaskValue);
            ACClassTaskValuePosEntityType.CreateAnnotations(aCClassTaskValuePos);
            ACClassTextEntityType.CreateAnnotations(aCClassText);
            ACClassWFEntityType.CreateAnnotations(aCClassWF);
            ACClassWFEdgeEntityType.CreateAnnotations(aCClassWFEdge);
            ACPackageEntityType.CreateAnnotations(aCPackage);
            ACProgramEntityType.CreateAnnotations(aCProgram);
            ACProgramConfigEntityType.CreateAnnotations(aCProgramConfig);
            ACProgramLogEntityType.CreateAnnotations(aCProgramLog);
            ACProgramLogPropertyLogEntityType.CreateAnnotations(aCProgramLogPropertyLog);
            ACProgramLogTaskEntityType.CreateAnnotations(aCProgramLogTask);
            ACProjectEntityType.CreateAnnotations(aCProject);
            ACPropertyLogEntityType.CreateAnnotations(aCPropertyLog);
            ACPropertyLogRuleEntityType.CreateAnnotations(aCPropertyLogRule);
            ControlScriptSyncInfoEntityType.CreateAnnotations(controlScriptSyncInfo);
            DBSyncerVersionEntityType.CreateAnnotations(dBSyncerVersion);
            DbSyncerInfoEntityType.CreateAnnotations(dbSyncerInfo);
            DbSyncerInfoContextEntityType.CreateAnnotations(dbSyncerInfoContext);
            MsgAlarmLogEntityType.CreateAnnotations(msgAlarmLog);
            VBConfigEntityType.CreateAnnotations(vBConfig);
            VBGroupEntityType.CreateAnnotations(vBGroup);
            VBGroupRightEntityType.CreateAnnotations(vBGroupRight);
            VBLanguageEntityType.CreateAnnotations(vBLanguage);
            VBLicenseEntityType.CreateAnnotations(vBLicense);
            VBNoConfigurationEntityType.CreateAnnotations(vBNoConfiguration);
            VBSystemEntityType.CreateAnnotations(vBSystem);
            VBSystemColumnsEntityType.CreateAnnotations(vBSystemColumns);
            VBTranslationViewEntityType.CreateAnnotations(vBTranslationView);
            VBUserEntityType.CreateAnnotations(vBUser);
            VBUserACClassDesignEntityType.CreateAnnotations(vBUserACClassDesign);
            VBUserACProjectEntityType.CreateAnnotations(vBUserACProject);
            VBUserGroupEntityType.CreateAnnotations(vBUserGroup);
            VBUserInstanceEntityType.CreateAnnotations(vBUserInstance);

            AddAnnotation("ProductVersion", "9.0.9");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
