// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using gip.core.datamodel;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(iPlusV5Context), typeof(iPlusV5ContextModel))]
