//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gip.tool.installerAndUpdater.TextResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gip.tool.installerAndUpdater.TextResources.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BtnBrowse {
            get {
                return ResourceManager.GetString("BtnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string BtnConfigure {
            get {
                return ResourceManager.GetString("BtnConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string BtnExit {
            get {
                return ResourceManager.GetString("BtnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string BtnFinish {
            get {
                return ResourceManager.GetString("BtnFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Agree.
        /// </summary>
        public static string BtnIAgree {
            get {
                return ResourceManager.GetString("BtnIAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string BtnInstall {
            get {
                return ResourceManager.GetString("BtnInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install updates.
        /// </summary>
        public static string BtnInstallUpdates {
            get {
                return ResourceManager.GetString("BtnInstallUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string BtnNext {
            get {
                return ResourceManager.GetString("BtnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string BtnRefresh {
            get {
                return ResourceManager.GetString("BtnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback.
        /// </summary>
        public static string BtnRollback {
            get {
                return ResourceManager.GetString("BtnRollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string BtnSkipDB {
            get {
                return ResourceManager.GetString("BtnSkipDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start iPlus.
        /// </summary>
        public static string BtnStartVB {
            get {
                return ResourceManager.GetString("BtnStartVB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string BtnUninstall {
            get {
                return ResourceManager.GetString("BtnUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlus version.
        /// </summary>
        public static string CbAppVersion {
            get {
                return ResourceManager.GetString("CbAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string CbDBAuthentication {
            get {
                return ResourceManager.GetString("CbDBAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string CbiRollbackManualAuto {
            get {
                return ResourceManager.GetString("CbiRollbackManualAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string CbiRollbackManualManual {
            get {
                return ResourceManager.GetString("CbiRollbackManualManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server authentication.
        /// </summary>
        public static string CbiSqlServerSqlAuth {
            get {
                return ResourceManager.GetString("CbiSqlServerSqlAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows authentication.
        /// </summary>
        public static string CbiSqlServerWinAuth {
            get {
                return ResourceManager.GetString("CbiSqlServerWinAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create iPlus shortcut on desktop..
        /// </summary>
        public static string ChDesktopShortcut {
            get {
                return ResourceManager.GetString("ChDesktopShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking run ....
        /// </summary>
        public static string CheckForUpdateStatus1 {
            get {
                return ResourceManager.GetString("CheckForUpdateStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string CheckForUpdateStatus2 {
            get {
                return ResourceManager.GetString("CheckForUpdateStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The :connect command &apos;{0}&apos; contains an invalid data source.
        /// </summary>
        public static string CONNECTSYNTAXEXCEPTIONFORMAT {
            get {
                return ResourceManager.GetString("CONNECTSYNTAXEXCEPTIONFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to MSSQL Server..
        /// </summary>
        public static string DBProgress0 {
            get {
                return ResourceManager.GetString("DBProgress0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to MSSQL Server..
        /// </summary>
        public static string DBProgress10 {
            get {
                return ResourceManager.GetString("DBProgress10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration is finished. Click Next to continue..
        /// </summary>
        public static string DBProgress100 {
            get {
                return ResourceManager.GetString("DBProgress100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database insert process started..
        /// </summary>
        public static string DBProgress30 {
            get {
                return ResourceManager.GetString("DBProgress30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database insert process finished.
        /// </summary>
        public static string DBProgress70 {
            get {
                return ResourceManager.GetString("DBProgress70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.config has been configured.
        /// </summary>
        public static string DBProgress75 {
            get {
                return ResourceManager.GetString("DBProgress75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback disabled.
        /// </summary>
        public static string ListRollbackOptionDisabled {
            get {
                return ResourceManager.GetString("ListRollbackOptionDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback enabled (Automatic database backup).
        /// </summary>
        public static string ListRollbackOptionEnabledAutomatic {
            get {
                return ResourceManager.GetString("ListRollbackOptionEnabledAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback enabled (Manual database backup).
        /// </summary>
        public static string ListRollbackOptionEnabledManual {
            get {
                return ResourceManager.GetString("ListRollbackOptionEnabledManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MsgBoxNo {
            get {
                return ResourceManager.GetString("MsgBoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MsgBoxOk {
            get {
                return ResourceManager.GetString("MsgBoxOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MsgBoxYes {
            get {
                return ResourceManager.GetString("MsgBoxYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want cancel the installation process?.
        /// </summary>
        public static string MsgCancel {
            get {
                return ResourceManager.GetString("MsgCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel installation.
        /// </summary>
        public static string MsgCancelHeader {
            get {
                return ResourceManager.GetString("MsgCancelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want cancel the update process?.
        /// </summary>
        public static string MsgCancelUpdate {
            get {
                return ResourceManager.GetString("MsgCancelUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel update.
        /// </summary>
        public static string MsgCancelUpdateHeader {
            get {
                return ResourceManager.GetString("MsgCancelUpdateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string MsgConnecting {
            get {
                return ResourceManager.GetString("MsgConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} database already exist, please delete this database and click Yes to continue or No to skip this step..
        /// </summary>
        public static string MsgDBAlreadyExist {
            get {
                return ResourceManager.GetString("MsgDBAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password can&apos;t be empty!.
        /// </summary>
        public static string MsgDBUserOrPassEmpty {
            get {
                return ResourceManager.GetString("MsgDBUserOrPassEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MsgErrorHeader {
            get {
                return ResourceManager.GetString("MsgErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MsgHeaderWarning {
            get {
                return ResourceManager.GetString("MsgHeaderWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string MsgLoading {
            get {
                return ResourceManager.GetString("MsgLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password! Try again with correct username and password..
        /// </summary>
        public static string MsgLoginWrongCred {
            get {
                return ResourceManager.GetString("MsgLoginWrongCred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong credentials.
        /// </summary>
        public static string MsgLoginWrongCredHeader {
            get {
                return ResourceManager.GetString("MsgLoginWrongCredHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? You will lose all your data!.
        /// </summary>
        public static string MsgRollbackDisabledNext {
            get {
                return ResourceManager.GetString("MsgRollbackDisabledNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MsgRollbackManualHeader {
            get {
                return ResourceManager.GetString("MsgRollbackManualHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing backup file.
        /// </summary>
        public static string MsgRollbackManualMissingFileHeader {
            get {
                return ResourceManager.GetString("MsgRollbackManualMissingFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing database backup file! Please select a database backup file..
        /// </summary>
        public static string MsgRollbackManualMissingFileText {
            get {
                return ResourceManager.GetString("MsgRollbackManualMissingFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to continue? You will lose all data from the current application version!.
        /// </summary>
        public static string MsgRollbackManualText {
            get {
                return ResourceManager.GetString("MsgRollbackManualText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong file type.
        /// </summary>
        public static string MsgRollbackManualWrongFileTypeHeader {
            get {
                return ResourceManager.GetString("MsgRollbackManualWrongFileTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong file type! Please select appropriate file..
        /// </summary>
        public static string MsgRollbackManualWrongFileTypeText {
            get {
                return ResourceManager.GetString("MsgRollbackManualWrongFileTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup file doesn´t end with .bak extension..
        /// </summary>
        public static string MsgRollbackWrongBackupFileType {
            get {
                return ResourceManager.GetString("MsgRollbackWrongBackupFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name can&apos;t be empty!.
        /// </summary>
        public static string MsgServerNameEmpty {
            get {
                return ResourceManager.GetString("MsgServerNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the SQL Server name, username and password if you use SQL server authentication..
        /// </summary>
        public static string MsgSqlErrorNoConnection {
            get {
                return ResourceManager.GetString("MsgSqlErrorNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role of the current user is not serveradmin..
        /// </summary>
        public static string MsgSqlErrorUserNotSysAdmin {
            get {
                return ResourceManager.GetString("MsgSqlErrorUserNotSysAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MsgUninstallHeader {
            get {
                return ResourceManager.GetString("MsgUninstallHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to uninstall application?.
        /// </summary>
        public static string MsgUninstallText {
            get {
                return ResourceManager.GetString("MsgUninstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MsgUpdateRollbackOptionHeader {
            get {
                return ResourceManager.GetString("MsgUpdateRollbackOptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue?.
        /// </summary>
        public static string MsgUpdateRollbackOptionText {
            get {
                return ResourceManager.GetString("MsgUpdateRollbackOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation installation ....
        /// </summary>
        public static string OperationCancel {
            get {
                return ResourceManager.GetString("OperationCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed..
        /// </summary>
        public static string OperationCompleted {
            get {
                return ResourceManager.GetString("OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing update ....
        /// </summary>
        public static string OperationCompleteUpdate {
            get {
                return ResourceManager.GetString("OperationCompleteUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating installation folder ....
        /// </summary>
        public static string OperationCreateFolder {
            get {
                return ResourceManager.GetString("OperationCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading application ....
        /// </summary>
        public static string OperationDownloadApp {
            get {
                return ResourceManager.GetString("OperationDownloadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading database ....
        /// </summary>
        public static string OperationDownloadDB {
            get {
                return ResourceManager.GetString("OperationDownloadDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update ....
        /// </summary>
        public static string OperationDownloadUpdate {
            get {
                return ResourceManager.GetString("OperationDownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed..
        /// </summary>
        public static string OperationFinishUpdate {
            get {
                return ResourceManager.GetString("OperationFinishUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to update ....
        /// </summary>
        public static string OperationPrepareUpdate {
            get {
                return ResourceManager.GetString("OperationPrepareUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback is completed..
        /// </summary>
        public static string OperationRollbackCompleted {
            get {
                return ResourceManager.GetString("OperationRollbackCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database restore in progress ....
        /// </summary>
        public static string OperationRollbackRestoreDatabase {
            get {
                return ResourceManager.GetString("OperationRollbackRestoreDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring previous application version ....
        /// </summary>
        public static string OperationRollbackRestorePrevAppVersion {
            get {
                return ResourceManager.GetString("OperationRollbackRestorePrevAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback operation start ....
        /// </summary>
        public static string OperationRollbackStart {
            get {
                return ResourceManager.GetString("OperationRollbackStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling current application version ....
        /// </summary>
        public static string OperationRollbackUninstallCurrentVersion {
            get {
                return ResourceManager.GetString("OperationRollbackUninstallCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking database ....
        /// </summary>
        public static string OperationRollbackUnpackDatabase {
            get {
                return ResourceManager.GetString("OperationRollbackUnpackDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting desktop shortcut ....
        /// </summary>
        public static string OperationSetShortcut {
            get {
                return ResourceManager.GetString("OperationSetShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking application ....
        /// </summary>
        public static string OperationUnpackApp {
            get {
                return ResourceManager.GetString("OperationUnpackApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking database ....
        /// </summary>
        public static string OperationUnpackDB {
            get {
                return ResourceManager.GetString("OperationUnpackDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking update ....
        /// </summary>
        public static string OperationUnpackUpdate {
            get {
                return ResourceManager.GetString("OperationUnpackUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string RbUninstallRemoveUserDataNo {
            get {
                return ResourceManager.GetString("RbUninstallRemoveUserDataNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string RbUninstallRemoveUserDataYes {
            get {
                return ResourceManager.GetString("RbUninstallRemoveUserDataYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option rollback disabled - restores application to previously available versions with initial database. You will lose all data from the application, including application configuration(App.config). This option is not recommended..
        /// </summary>
        public static string RollbackOptionDescriptionDisabled {
            get {
                return ResourceManager.GetString("RollbackOptionDescriptionDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option rollback enabled with automatic database backup - restores application to previous version with all your data. This option requires database login with the user role sysadmin..
        /// </summary>
        public static string RollbackOptionDescriptionEnabledAutomatic {
            get {
                return ResourceManager.GetString("RollbackOptionDescriptionEnabledAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option rollback enabled with manual database backup - provides restore application to previous version with all your data. Please backup your database NOW, then continue with update! If you don&apos;t backup your database, you will lose all your data..
        /// </summary>
        public static string RollbackOptionDescriptionEnabledManual {
            get {
                return ResourceManager.GetString("RollbackOptionDescriptionEnabledManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The :setvar command &apos;{0}&apos; contains an invalid variable definition.
        /// </summary>
        public static string SETVARSYNTAXEXCEPTIONFORMAT {
            get {
                return ResourceManager.GetString("SETVARSYNTAXEXCEPTIONFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The :!! command &apos;{0}&apos; contains an invalid command.
        /// </summary>
        public static string SHELLSYNTAXEXCEPTIONFORMAT {
            get {
                return ResourceManager.GetString("SHELLSYNTAXEXCEPTIONFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.microsoft.com/en-us/sql-server/sql-server-downloads.
        /// </summary>
        public static string SqlServerDownloadPage {
            get {
                return ResourceManager.GetString("SqlServerDownloadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlus requires Microsoft&apos;s SQL server database software.
        ///If you do not have a SQL server available on your network or are installed on your local machine, please download the free Express or Developer version from the Microsoft page.
        ///When the SQL server installation is complete, please proceed with this installation..
        /// </summary>
        public static string SqlServerInfoInstall {
            get {
                return ResourceManager.GetString("SqlServerInfoInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gipSoft d.o.o. - All rights reserved..
        /// </summary>
        public static string TbAllRightsReserved {
            get {
                return ResourceManager.GetString("TbAllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select which version of iPlus you want install..
        /// </summary>
        public static string TbApplicationVersion {
            get {
                return ResourceManager.GetString("TbApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New application version is available. Click Next to continue with update..
        /// </summary>
        public static string TbCheckForUpdateAvailableNewUpdates {
            get {
                return ResourceManager.GetString("TbCheckForUpdateAvailableNewUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string TbCheckForUpdateHeader {
            get {
                return ResourceManager.GetString("TbCheckForUpdateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updater checking for iPlus updates ....
        /// </summary>
        public static string TbCheckForUpdateInfo {
            get {
                return ResourceManager.GetString("TbCheckForUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application is up to date. Click Exit to close updater..
        /// </summary>
        public static string TbCheckForUpdateNoNewUpdates {
            get {
                return ResourceManager.GetString("TbCheckForUpdateNoNewUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database configuration.
        /// </summary>
        public static string TbDBHeader {
            get {
                return ResourceManager.GetString("TbDBHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter required MSSQL Server information. The server role of the user must be sysadmin..
        /// </summary>
        public static string TbDBInfo {
            get {
                return ResourceManager.GetString("TbDBInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Configure for automatic configuration of the App.config file and automatic insert of the iPlus database into MSSQL Server. If you want to manually configure the App.config and insert the database into MSSQL server, click Skip..
        /// </summary>
        public static string TbDBInfo2 {
            get {
                return ResourceManager.GetString("TbDBInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration progress.
        /// </summary>
        public static string TbDBProgress {
            get {
                return ResourceManager.GetString("TbDBProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, while iPlus installer finishes the database configuration..
        /// </summary>
        public static string TbDBProgressInfo {
            get {
                return ResourceManager.GetString("TbDBProgressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name.
        /// </summary>
        public static string TbDBServerName {
            get {
                return ResourceManager.GetString("TbDBServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string TbDBServerPassword {
            get {
                return ResourceManager.GetString("TbDBServerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string TbDBServerUserName {
            get {
                return ResourceManager.GetString("TbDBServerUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder.
        /// </summary>
        public static string TbDestinationFolder {
            get {
                return ResourceManager.GetString("TbDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string TbFinishHeader {
            get {
                return ResourceManager.GetString("TbFinishHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation is successfully completed..
        /// </summary>
        public static string TbFinishInfo {
            get {
                return ResourceManager.GetString("TbFinishInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback is successfully completed..
        /// </summary>
        public static string TbFinishInfoRollback {
            get {
                return ResourceManager.GetString("TbFinishInfoRollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use iPlus.
        /// </summary>
        public static string TbHowToUseiPlus {
            get {
                return ResourceManager.GetString("TbHowToUseiPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install options.
        /// </summary>
        public static string TbInstallHeader {
            get {
                return ResourceManager.GetString("TbInstallHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup will install iPlus in the following folder. To install in a different folder click Browse and select another folder..
        /// </summary>
        public static string TbInstallLocationInfo {
            get {
                return ResourceManager.GetString("TbInstallLocationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation is completed. Click Next to continue..
        /// </summary>
        public static string TbInstallProgressCompleted {
            get {
                return ResourceManager.GetString("TbInstallProgressCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation progress.
        /// </summary>
        public static string TbInstallProgressHeader {
            get {
                return ResourceManager.GetString("TbInstallProgressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, while iPlus installer completes the installation..
        /// </summary>
        public static string TbInstallProgressInfo {
            get {
                return ResourceManager.GetString("TbInstallProgressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total progress.
        /// </summary>
        public static string TbInstallTotalProgress {
            get {
                return ResourceManager.GetString("TbInstallTotalProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Agreement.
        /// </summary>
        public static string TbLicenseAgreement {
            get {
                return ResourceManager.GetString("TbLicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the license terms before installing iPlus..
        /// </summary>
        public static string TbLicenseInfo {
            get {
                return ResourceManager.GetString("TbLicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you accept the terms of the agrement, click I agree to continue. You must accept the agreement to install iPlus..
        /// </summary>
        public static string TbLicenseInfo2 {
            get {
                return ResourceManager.GetString("TbLicenseInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIPSOFT D.O.O. SOFTWARE LICENSE TERMS
        ///
        ///IPLUS, IPLUS.MES
        ///
        ///These license terms are an agreement between you and GIPSOFT D.O.O.. They apply to the software named above. The terms also apply to any GIPSOFT services and updates for the software, except to the extent those have different terms. 
        ///BY INSTALLING, HAVING INSTALLED, SUBSCRIBING TO, OR USING THE SOFTWARE, YOU ACCEPT THIS AGREEMENT (INCLUDING ANY MODIFICATIONS MADE TO IT FROM TIME TO TIME).  IF YOU DO NOT ACCEPT THIS AGREEMENT, DO NOT INSTALL, HAVE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TbLicenseText {
            get {
                return ResourceManager.GetString("TbLicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string TbLoginEmail {
            get {
                return ResourceManager.GetString("TbLoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login with your gip account. Enter a valid e-mail address and password..
        /// </summary>
        public static string TbLoginInfo {
            get {
                return ResourceManager.GetString("TbLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Login to continue with installation..
        /// </summary>
        public static string TbLoginInfo2 {
            get {
                return ResourceManager.GetString("TbLoginInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string TbLoginPassword {
            get {
                return ResourceManager.GetString("TbLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL-Server® is a registred trademark of the Microsoft Corporation..
        /// </summary>
        public static string TbMicrosoftTrademark {
            get {
                return ResourceManager.GetString("TbMicrosoftTrademark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlus installation and update program.
        /// </summary>
        public static string TbProgramMaintHeader {
            get {
                return ResourceManager.GetString("TbProgramMaintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an operation and click Next to continue.
        /// </summary>
        public static string TbProgramMaintInfo {
            get {
                return ResourceManager.GetString("TbProgramMaintInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback.
        /// </summary>
        public static string TbProgramMaintRollback {
            get {
                return ResourceManager.GetString("TbProgramMaintRollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string TbProgramMaintUninstall {
            get {
                return ResourceManager.GetString("TbProgramMaintUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string TbProgramMaintUpdate {
            get {
                return ResourceManager.GetString("TbProgramMaintUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback application version:.
        /// </summary>
        public static string TbRollbackAppVersion {
            get {
                return ResourceManager.GetString("TbRollbackAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available backup database files:.
        /// </summary>
        public static string TbRollbackAutoDBFile {
            get {
                return ResourceManager.GetString("TbRollbackAutoDBFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Next to continue with rollback.....
        /// </summary>
        public static string TbRollbackAutoInfo {
            get {
                return ResourceManager.GetString("TbRollbackAutoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback application to previous version.
        /// </summary>
        public static string TbRollbackAutoPrevVersion {
            get {
                return ResourceManager.GetString("TbRollbackAutoPrevVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: If you use a remote SQL server, enter a backup file path from remote machine!.
        /// </summary>
        public static string TbRollbackBackupFilePathInfo {
            get {
                return ResourceManager.GetString("TbRollbackBackupFilePathInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback database connection.
        /// </summary>
        public static string TbRollbackDBHeader {
            get {
                return ResourceManager.GetString("TbRollbackDBHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Next to continue with rollback operation ....
        /// </summary>
        public static string TbRollbackDBInfo {
            get {
                return ResourceManager.GetString("TbRollbackDBInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version changelog.
        /// </summary>
        public static string TbRollbackDisabledChangeLog {
            get {
                return ResourceManager.GetString("TbRollbackDisabledChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose version for rollback.
        /// </summary>
        public static string TbRollbackDisabledChooseVersion {
            get {
                return ResourceManager.GetString("TbRollbackDisabledChooseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback.
        /// </summary>
        public static string TbRollbackDisabledHeader {
            get {
                return ResourceManager.GetString("TbRollbackDisabledHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback to initial application version with initial database. If you continue with rollback, you will lose all your data!.
        /// </summary>
        public static string TbRollbackDisabledInfo {
            get {
                return ResourceManager.GetString("TbRollbackDisabledInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Next to continue with rollback ....
        /// </summary>
        public static string TbRollbackDisabledInfo2 {
            get {
                return ResourceManager.GetString("TbRollbackDisabledInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous versions are unavailable..
        /// </summary>
        public static string TbRollbackDisabledVersionUnavailable {
            get {
                return ResourceManager.GetString("TbRollbackDisabledVersionUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose database backup file (*.bak).
        /// </summary>
        public static string TbRollbackManualDBFile {
            get {
                return ResourceManager.GetString("TbRollbackManualDBFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose database restore option.
        /// </summary>
        public static string TbRollbackManualDBRestoreOption {
            get {
                return ResourceManager.GetString("TbRollbackManualDBRestoreOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback.
        /// </summary>
        public static string TbRollbackManualHeader {
            get {
                return ResourceManager.GetString("TbRollbackManualHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback application to previous version.
        /// </summary>
        public static string TbRollbackManualInfo {
            get {
                return ResourceManager.GetString("TbRollbackManualInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Rollback to start rollback operation..
        /// </summary>
        public static string TbRollbackManualInfo2 {
            get {
                return ResourceManager.GetString("TbRollbackManualInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Next to continue with rollback ....
        /// </summary>
        public static string TbRollbackManualInfo2Next {
            get {
                return ResourceManager.GetString("TbRollbackManualInfo2Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback progress.
        /// </summary>
        public static string TbRollbackProgressHeader {
            get {
                return ResourceManager.GetString("TbRollbackProgressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, rollback operation is in progress.
        /// </summary>
        public static string TbRollbackProgressInfo {
            get {
                return ResourceManager.GetString("TbRollbackProgressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback info.
        /// </summary>
        public static string TbRollbackProgressInfo2 {
            get {
                return ResourceManager.GetString("TbRollbackProgressInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback run ....
        /// </summary>
        public static string TbRollbackProgressRun {
            get {
                return ResourceManager.GetString("TbRollbackProgressRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for MSSQL Server.
        /// </summary>
        public static string TbSqlCheckHeader {
            get {
                return ResourceManager.GetString("TbSqlCheckHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlus installer seraching for available MSSQL Servers ....
        /// </summary>
        public static string TbSqlCheckInfo {
            get {
                return ResourceManager.GetString("TbSqlCheckInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search is completed. Click Next to continue..
        /// </summary>
        public static string TbSqlCheckInfo2 {
            get {
                return ResourceManager.GetString("TbSqlCheckInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching ....
        /// </summary>
        public static string TbSqlCheckSearching {
            get {
                return ResourceManager.GetString("TbSqlCheckSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string TbSqlCheckWarning {
            get {
                return ResourceManager.GetString("TbSqlCheckWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows service SQL Server Browser missing..
        /// </summary>
        public static string TbSqlCheckWarningServiceMissing {
            get {
                return ResourceManager.GetString("TbSqlCheckWarningServiceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlus installer needs SQL Server Browser service for searching available SQL servers. Click Next to continue to the next installation page where you&apos;ll need to manually enter a SQL server name..
        /// </summary>
        public static string TbSqlCheckWarningServiceMissingInfo {
            get {
                return ResourceManager.GetString("TbSqlCheckWarningServiceMissingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows service SQL Server Browser not running..
        /// </summary>
        public static string TbSqlCheckWarningServiceNotRunning {
            get {
                return ResourceManager.GetString("TbSqlCheckWarningServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPlus installer needs SQL Server Browser service for searching available SQL servers. If you want to automatically search SQL servers, start the SQL Server-Browser service in Windows Service Management and click the Refresh button. Click Next if you want enter SQL server name manually..
        /// </summary>
        public static string TbSqlCheckWarningServiceNotRunningInfo {
            get {
                return ResourceManager.GetString("TbSqlCheckWarningServiceNotRunningInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL-Server download page.
        /// </summary>
        public static string TbSqlServerDownload {
            get {
                return ResourceManager.GetString("TbSqlServerDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will be uninstalled from the following folder..
        /// </summary>
        public static string TbUninstallFollowingFolder {
            get {
                return ResourceManager.GetString("TbUninstallFollowingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string TbUninstallHeader {
            get {
                return ResourceManager.GetString("TbUninstallHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Uninstall to start the uninstallation..
        /// </summary>
        public static string TbUninstallInfo {
            get {
                return ResourceManager.GetString("TbUninstallInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall progress.
        /// </summary>
        public static string TbUninstallProgressHeader {
            get {
                return ResourceManager.GetString("TbUninstallProgressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling is in progress, please wait ....
        /// </summary>
        public static string TbUninstallProgressInfo {
            get {
                return ResourceManager.GetString("TbUninstallProgressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall is finished. Click Finish to exit..
        /// </summary>
        public static string TbUninstallProgressInfo2 {
            get {
                return ResourceManager.GetString("TbUninstallProgressInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will be removed from your Computer.
        /// </summary>
        public static string TbUninstallRemove {
            get {
                return ResourceManager.GetString("TbUninstallRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user data?.
        /// </summary>
        public static string TbUninstallRemoveUserData {
            get {
                return ResourceManager.GetString("TbUninstallRemoveUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is running, please close the application before starting the updater..
        /// </summary>
        public static string TbUpdateApplicationStillRunning {
            get {
                return ResourceManager.GetString("TbUpdateApplicationStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update info.
        /// </summary>
        public static string TbUpdateChangeLogHeader {
            get {
                return ResourceManager.GetString("TbUpdateChangeLogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update change log.
        /// </summary>
        public static string TbUpdateChangeLogInfo {
            get {
                return ResourceManager.GetString("TbUpdateChangeLogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Install updates to start update ....
        /// </summary>
        public static string TbUpdateChangeLogInfoInstall {
            get {
                return ResourceManager.GetString("TbUpdateChangeLogInfoInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update is completed. Click Start iPlus to apply update..
        /// </summary>
        public static string TbUpdateProgressCompleted {
            get {
                return ResourceManager.GetString("TbUpdateProgressCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update progress.
        /// </summary>
        public static string TbUpdateProgressHeader {
            get {
                return ResourceManager.GetString("TbUpdateProgressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, while iPlus updater completes the update action..
        /// </summary>
        public static string TbUpdateProgressInfo {
            get {
                return ResourceManager.GetString("TbUpdateProgressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a database backup file name (*.bak).
        /// </summary>
        public static string TbUpdateRollbackAutoDBFile {
            get {
                return ResourceManager.GetString("TbUpdateRollbackAutoDBFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database backup - login.
        /// </summary>
        public static string TbUpdateRollbackDBHeader {
            get {
                return ResourceManager.GetString("TbUpdateRollbackDBHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Next to continue or if you want skip this step click on Skip ....
        /// </summary>
        public static string TbUpdateRollbackDBInfo {
            get {
                return ResourceManager.GetString("TbUpdateRollbackDBInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Next to continue ....
        /// </summary>
        public static string TbUpdateRollbackInfo {
            get {
                return ResourceManager.GetString("TbUpdateRollbackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Next to continue and please wait database connection ....
        /// </summary>
        public static string TbUpdateRollbackInfoAuto {
            get {
                return ResourceManager.GetString("TbUpdateRollbackInfoAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Rollback option.
        /// </summary>
        public static string TbUpdateRollbackOptionsChoose {
            get {
                return ResourceManager.GetString("TbUpdateRollbackOptionsChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback option description.
        /// </summary>
        public static string TbUpdateRollbackOptionsDescription {
            get {
                return ResourceManager.GetString("TbUpdateRollbackOptionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback options.
        /// </summary>
        public static string TbUpdateRollbackOptionsHeader {
            get {
                return ResourceManager.GetString("TbUpdateRollbackOptionsHeader", resourceCulture);
            }
        }
    }
}
