//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gip.core.reporthandler.avui.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Calibri")]
        public global::System.Windows.Media.FontFamily Options_DefaultFont {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["Options_DefaultFont"]));
            }
            set {
                this["Options_DefaultFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double Options_DefaultFontSize {
            get {
                return ((double)(this["Options_DefaultFontSize"]));
            }
            set {
                this["Options_DefaultFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Options_SpellCheck {
            get {
                return ((bool)(this["Options_SpellCheck"]));
            }
            set {
                this["Options_SpellCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MainWindow_ShowRuler {
            get {
                return ((bool)(this["MainWindow_ShowRuler"]));
            }
            set {
                this["MainWindow_ShowRuler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Options_RulerMeasurement {
            get {
                return ((int)(this["Options_RulerMeasurement"]));
            }
            set {
                this["Options_RulerMeasurement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Options_Tabs_SizeMode {
            get {
                return ((int)(this["Options_Tabs_SizeMode"]));
            }
            set {
                this["Options_Tabs_SizeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCommonEditGroup {
            get {
                return ((bool)(this["ShowCommonEditGroup"]));
            }
            set {
                this["ShowCommonEditGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCommonViewGroup {
            get {
                return ((bool)(this["ShowCommonViewGroup"]));
            }
            set {
                this["ShowCommonViewGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCommonInsertGroup {
            get {
                return ((bool)(this["ShowCommonInsertGroup"]));
            }
            set {
                this["ShowCommonInsertGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCommonToolsGroup {
            get {
                return ((bool)(this["ShowCommonToolsGroup"]));
            }
            set {
                this["ShowCommonToolsGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCommonFormatGroup {
            get {
                return ((bool)(this["ShowCommonFormatGroup"]));
            }
            set {
                this["ShowCommonFormatGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MainWindow_ShowStatusBar {
            get {
                return ((bool)(this["MainWindow_ShowStatusBar"]));
            }
            set {
                this["MainWindow_ShowStatusBar"] = value;
            }
        }
    }
}
